### ISSUE TITLE
Ссылка на сборку устарела (можно выложить в релизах проекта)

### ISSUE THREAD

**Issue by tarik02** [KoMaTo3/LightTest#1]

**Comment by tarik02** [comment]
А также сам собрать не могу т.к. нет кое-какого opengl_minimal

**Comment by KoMaTo3** [comment]
Доброго времени суток, Taras.
Бинарник перезалил сюда (роскомнадзор, мать его за ногу)
https://scw.komato3.net/lighttest.zip
Сорцы opengl_minimal, тут по сути только работа с opengl
http://scw.komato3.net/opengl_minimal.zip
P.S. Если честно, весь этот алгоритм чисто CPUшный, это был мой личный
эксперимент/исследование, в современных реалиях удобнее/быстрее
использовать расчёты на GPU, на Хабре и не только не мало статей на эту
тему. В любом случае, спасибо за интерес.

вс, 20 янв. 2019 г. в 00:00, Taras <notifications@github.com>:

**Comment by tarik02** [comment]
Спасибо. Никак не могу разобраться, на хабре везде юнити. А именно проблема в том, как отрендерить в фреймбуфер толщиною в один пиксель, с видом сбоку (правильно?). Если я просто пробую рендерить со стороны в ортографической проекции, то плоские объекты становятся невидимыми.
